(******************************************************************************)
(*                                                                            *)
(*                Class Field Theory: Abelian Extensions                       *)
(*                                                                            *)
(*     Formalizes the classification of abelian extensions of number fields:  *)
(*     ideal class groups, Artin reciprocity law, Hilbert class field,        *)
(*     Takagi existence theorem. Proves abelian extensions correspond to      *)
(*     subgroups of the idele class group; unramified extensions biject       *)
(*     with ideal class group quotients.                                      *)
(*                                                                            *)
(*     "Die Theorie der algebraischen Zahlkörper ist eine der                 *)
(*     ruhmreichsten Errungenschaften der Mathematik."                        *)
(*     - David Hilbert, Zahlbericht, 1897                                     *)
(*                                                                            *)
(*     Author: Charles C. Norton                                              *)
(*     Date: January 7, 2026                                                  *)
(*     License: MIT                                                           *)
(*                                                                            *)
(******************************************************************************)
